### ISSUE TITLE
Store theme files as `.json5`

### ISSUE THREAD

**Issue by ThatOneCalculator** [revengeday/calckey-themes#1]
For example, https://github.com/revengeday/calckey-themes/blob/main/cyber-red-theme/cyber-red-theme.md should be `cyber-red-theme.json5`, so it can be highlighted better, and even listed in Misskey theme lists

**Comment by revengeday** [comment]
Thank you for the tip, I will adapt it directly!

**Comment by revengeday** [comment]
Fixed https://github.com/revengeday/calckey-themes/commit/674ccc13479c5284adced7da1e491a4551471d9d
